### ISSUE TITLE
Output writeline

### ISSUE THREAD

**Issue by RPA-kontor** [cloudhack/zeniverserpa_issues#10]
Hvor kan jeg se output fra en writeline?

**Comment by cloudhack** [comment]
Det kan du ikke lige nu. Det er derfor der er en "Log" aktivitet.
Men tænker det kunne være smart med et "output" vindue, til at fange Arguments og WriteLines. 
Vil "log" være godt nok indtil videre ?

**Comment by RPA-kontor** [comment]
Det er lige meget hvor outputtet stå, bare det er overskueligt og jeg ikke skal til at lede en hel log igennem. Jeg bruger nemlig mange writelines til at teste.

**Comment by cloudhack** [comment]
Good point. Jeg vil prøve og få det lavet asap ..

**Comment by cloudhack** [comment]
Jeg har været kreativ, og lavet noget helt andet.
Der er nu implementeret Breakpoints i roboten. med F9 ( eller højre klik's menuen ) kan man "sætte" et breakpoint, så stopper robot eksekvering når den når der til.
![image](https://user-images.githubusercontent.com/31153858/42962353-b8f928fa-8b91-11e8-8582-36b754a73f5e.png)
Når den stopper, vil egenskabs vinduet blive erstatet af et variable inspektions vindue, hvor i man kan se indholdet af alle variabler. Hvis en variable indeholder et advenceret object, vil man kunne lave "drill down" og se under egenskaber
![image](https://user-images.githubusercontent.com/31153858/42962508-118645ac-8b92-11e8-92bb-24e8b3fae067.png)
