### ISSUE TITLE
Opret variabler hvor de bruges. 

### ISSUE THREAD

**Issue by RPA-kontor** [cloudhack/zeniverserpa_issues#14]
ville være dejligt, hvis man kunne oprette variabler hvor variablen skal bruges. I uipath, trykker man CTRL+k og så oprettes variablen.

**Comment by cloudhack** [comment]
Den her vil jeg godt "gemme" lidt, den høre lidt sammen med #7
Det vil være enkelt at implementere, så snart vi har "kontrol" over source koden.

**Comment by cloudhack** [comment]
Man kan nu oprette variabler med den rigtige type, ved at trykke ctrl+K når man står i et felt
( Midlertidigt virker dette kune for VB workflows )
