### ISSUE TITLE
Foreslå variabler

### ISSUE THREAD

**Issue by RPA-kontor** [cloudhack/zeniverserpa_issues#16]
Når man bruger en oprettet variabel, vil det være lækkert, hvis koden foreslå variablen, når man bruger den i koden. Så man er fri for at tjekke det præcise navn i "Variables"

**Comment by cloudhack** [comment]
Den her vil jeg godt "gemme" lidt, den høre lidt sammen med #7 
Tænker det er enkelt at implementere, så snart vi har "kontrol" over source koden.

**Comment by cloudhack** [comment]
Prøvede først med "auto" popup af variable foreslag, men det blev hurtigt irreterende.
Så jeg har nu lavet en version hvor man kan trykke Ctrl+Space eller Ctrl+J så kommer der en liste af variabler. ( Ctrl+Space er standard  genvej til det samme i visual studio )
