### ISSUE TITLE
ElementClick

### ISSUE THREAD

**Issue by RPA-kontor** [cloudhack/zeniverserpa_issues#17]
Når jeg indsætter "Element Click" ser den sådan her ud, lige når man indsætter den: 
![elementclick](https://user-images.githubusercontent.com/40860868/42513382-4cff45c8-8446-11e8-8e5a-834c08ebb0c3.JPG)
Når du trykker på: 
![pil](https://user-images.githubusercontent.com/40860868/42513407-680e064c-8446-11e8-8efe-2c38c429c34c.JPG)
Ser det sådan her ud: 
![ned](https://user-images.githubusercontent.com/40860868/42513428-7306707a-8446-11e8-9fd4-e817610e11ad.JPG)

Når jeg så klikker på "Click on screen", blikker skærmen bare og ender tilbage i RPA-designeren.

**Comment by cloudhack** [comment]
Der er nu lagt en ny version op, som automatisk fjerner "Click on screen" knappen, når offsets ikke er undersøttet.
