### ISSUE TITLE
"Record" kan ikke stoppes, efter netværks udfald

### ISSUE THREAD

**Issue by RPA-kontor** [cloudhack/zeniverserpa_issues#19]
Hvordan lukker jeg "record" nu virker det ikke længere at trykke f12

**Comment by cloudhack** [comment]
Det bliver du nok nød til at vise mig.
For virker fint på mine udviklings maskiner, og når jeg logger på jeres citrix server.
Giv mig gerne et kald, når du er klar.

**Comment by cloudhack** [comment]
Efter intens testning, mener vi dette er fixet nu.
