### ISSUE TITLE
Bruger defineret Stop-knap under "record" og "Play"

### ISSUE THREAD

**Issue by RPA-kontor** [cloudhack/zeniverserpa_issues#20]
Det skal være at konfigurere hvilken knap man stopper "Record" med

**Comment by cloudhack** [comment]
Dette er nu implementeret. Man klikke i tekst feltet og vælger en tast/tastetur kobination
MainWindow -> Settings
![image](https://user-images.githubusercontent.com/31153858/42681731-cd9c8404-8688-11e8-82a5-263eb3727c5d.png)
