### ISSUE TITLE
Image Click

### ISSUE THREAD

**Issue by RPA-kontor** [cloudhack/zeniverserpa_issues#27]
Jeg får denne fejl, når jeg bruger "Image Click".

**Comment by RPA-kontor** [comment]
Ups, glemte lige at sende billedet med: 
![udklip](https://user-images.githubusercontent.com/40860868/44574106-b9d5fd80-a788-11e8-81a6-ce375ad89aeb.JPG)

**Comment by cloudhack** [comment]
Ud fra fejlen, ligner det nu mere at designeren har prøvet og lave et auto-save samtidig.
Har du stadig fejlen ? 
hvis du har, vil jeg rigtig gerne lige se det ske, f.eks via TeamViewer eller hvilket program vi skal bruge.
