### ISSUE TITLE
Fejlfinding

### ISSUE THREAD

**Issue by RPA-kontor** [cloudhack/zeniverserpa_issues#4]
- Det kunne være dejligt, hvis Robotten viser hvor fejlen opstår i et gennemløb. For eksempel en popup med en fejlmeddelelse. Jeg synes det er svært at fejlfinde.

**Comment by cloudhack** [comment]
Visual Tracking var ment som et værktøj til at netop det. 
Men kan godt se, det ikke altid er hensigtsmæssigt, skal se om der findes en måde at finde lokationen for en fejl, så designeren kan hoppe direkte til den aktivitet.

**Comment by cloudhack** [comment]
RPA designer vil nu hoppe til, og markere, den første aktivitet som fejler, hvis designer er åben.
Fejl og stacktrace vil stadig stå nede i log vinduet.
