### ISSUE TITLE
Stifinder

### ISSUE THREAD

**Issue by RPA-kontor** [cloudhack/zeniverserpa_issues#6]
- Når man skal bruge en fil, kunne det være fedt, at "stifinderen" popper op, når man trykker på:  "de tre prikker" ud fra "skrivefeltet"

**Comment by cloudhack** [comment]
Jeg forstår ikke helt hvilket felt du hentyder til. Kan du evt tilføje et screenshot eller navnet på aktiviteten ?

**Comment by RPA-kontor** [comment]
Det var de her tre prikker jeg snakkede om. 
![prikker](https://user-images.githubusercontent.com/40860868/42378237-e11ac7b4-8126-11e8-82e6-b2f2d8e75ddf.JPG)

**Comment by cloudhack** [comment]
Lige nøjagtig den knap, er "indbygget" i frameworket og lavet til at åbne et nyt vindue at indtaste i, så den kan jeg ikke ændre.
Men jeg har lavet en "..." knap i aktivitets designeren, som åbner en "Vælg fil dialog boks".
