### ISSUE TITLE
If-sætning 

### ISSUE THREAD

**Issue by RPA-kontor** [cloudhack/zeniverserpa_issues#7]
- Hvis "If-sætningerne" er længere end området hvor man skal skrive. se billede: 
![if](https://user-images.githubusercontent.com/40860868/42324816-d308a750-8053-11e8-9211-dd442f5220b7.png)

**Comment by cloudhack** [comment]
Ja, det er helt klar uhensigts mæssigt med den scrollbar som dækker det hele.
Vi bruger et 3 parts komponent til at give Auto Complete, men der er et par uhensigtmæssigheder i det komponent, som gør vi helt klar gerne vil skrive vores egen.
I de tilfælde kan du slå Intellisense fra, så bruger designeren den indbyggede editor.
( MainWindow -> Settings -> Intellisense )

**Comment by cloudhack** [comment]
Dette er nu fixet
( Midlertidigt kun for VB )
