### ISSUE TITLE
Husk vindues postion efter optagelse og afspilning

### ISSUE THREAD

**Issue by RPA-kontor** [cloudhack/zeniverserpa_issues#9]
RPA-designere forbliver ikke halvskærm, efter man for eksempel har anvendt "record" eller afspillet robotten.

**Comment by cloudhack** [comment]
Robotten burde nu være bedre til at respekter vinduet oprindeligt position efter at have være minimeret.
Vil du teste og lukke hvis du er enig ?

**Comment by RPA-kontor** [comment]
Jeg har lige testet, og kan ikke se nogen forskel fra før.

**Comment by cloudhack** [comment]
Er godkendt via email
